# Generated by Django 4.0.3 on 2022-04-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_annotation_remove_channel_id_channel_iuphar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='reference',
            field=models.CharField(blank=True, help_text='DOI for primary reference corresponding to PDB model. null ok', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='kegg',
            field=models.CharField(blank=True, help_text='KEGG Pathway Reference number (e.g., K04857), null ok', max_length=10, null=True),
        ),
    ]
