# Generated by Django 4.0.3 on 2022-04-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_channel_reference_alter_channel_kegg'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='fasta',
            field=models.TextField(blank=True, help_text='FASTA sequence for the primary channel subunit. null ok', max_length=5000, null=True),
        ),
    ]
